/**
 * Android Auto Backup ("Google Drive backup") fix.
 *
 * Google Drive Auto Backup has a 25 MB per-app quota. This app's files dir
 * contains two things that blow past it:
 *   - mbgl-offline.db  — MapLibre's tile cache (grows to tens of MB)
 *   - photos/          — full-resolution visit photos
 * Once the payload exceeds the quota, Android backs up NOTHING, so even the
 * small AsyncStorage database (the actual visit data) and the
 * parko-autobackup.json bundle never reach Google Drive.
 *
 * This plugin excludes the two large paths from cloud backup while keeping
 * everything else (databases, shared prefs, the JSON bundle) included.
 * Device-to-device transfer has no quota, so it is left at the default
 * (transfer everything, photos included).
 *
 * android/ is generated by prebuild (CNG), so this must be a config plugin —
 * direct edits to AndroidManifest.xml would be overwritten.
 */
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const FULL_BACKUP_CONTENT = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidBackupRules.js — do not edit by hand. -->
<!-- Used on Android 11 and lower. Only excludes: everything else is backed up. -->
<full-backup-content>
  <exclude domain="file" path="mbgl-offline.db" />
  <exclude domain="file" path="photos" />
</full-backup-content>
`;

const DATA_EXTRACTION_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidBackupRules.js — do not edit by hand. -->
<!-- Used on Android 12+. Only excludes: everything else is backed up. -->
<data-extraction-rules>
  <cloud-backup>
    <exclude domain="file" path="mbgl-offline.db" />
    <exclude domain="file" path="photos" />
  </cloud-backup>
</data-extraction-rules>
`;

function withBackupRulesXml(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const xmlDir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'full_backup_content.xml'), FULL_BACKUP_CONTENT);
      fs.writeFileSync(path.join(xmlDir, 'data_extraction_rules.xml'), DATA_EXTRACTION_RULES);
      return cfg;
    },
  ]);
}

function withBackupManifestAttributes(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.$['android:allowBackup'] = 'true';
    app.$['android:fullBackupContent'] = '@xml/full_backup_content';
    app.$['android:dataExtractionRules'] = '@xml/data_extraction_rules';
    return cfg;
  });
}

module.exports = function withAndroidBackupRules(config) {
  return withBackupManifestAttributes(withBackupRulesXml(config));
};
