import { ImageSourcePropType } from 'react-native';

/**
 * AUTO-GENERATED by scripts/fetch-park-photos.mjs — do not edit by hand.
 * WebP heroes (max 960×640, q72) from Wikimedia Commons.
 * Attribution lives in assets/parks/attribution.json and MUST stay shipped
 * with the app (Commons licenses require author + license credit).
 */
export const parkPhotos: Record<string, ImageSourcePropType> = {
  'fort-mistrzejowice': require('../../assets/parks/fort-mistrzejowice.webp'),
  'park-fort-2-kosciuszko': require('../../assets/parks/park-fort-2-kosciuszko.webp'),
  'park-szwedzki': require('../../assets/parks/park-szwedzki.webp'),
  'park-ratuszowy': require('../../assets/parks/park-ratuszowy.webp'),
  'park-klasztorna': require('../../assets/parks/park-klasztorna.webp'),
  'park-im-stefana-zeromskiego': require('../../assets/parks/park-im-stefana-zeromskiego.webp'),
  'park-wadow': require('../../assets/parks/park-wadow.webp'),
  'park-jana-matejki': require('../../assets/parks/park-jana-matejki.webp'),
  'park-tysiaclecia': require('../../assets/parks/park-tysiaclecia.webp'),
  'fort-batowice': require('../../assets/parks/fort-batowice.webp'),
  'park-lotnikow-polskich': require('../../assets/parks/park-lotnikow-polskich.webp'),
  'planty-nowackiego': require('../../assets/parks/planty-nowackiego.webp'),
  'park-stacja-wisla': require('../../assets/parks/park-stacja-wisla.webp'),
  'park-im-wojciecha-bednarskiego': require('../../assets/parks/park-im-wojciecha-bednarskiego.webp'),
  'park-przy-dworze-czeczow': require('../../assets/parks/park-przy-dworze-czeczow.webp'),
  'park-jerzmanowskich': require('../../assets/parks/park-jerzmanowskich.webp'),
  'park-sw-wincentego-a-paulo': require('../../assets/parks/park-sw-wincentego-a-paulo.webp'),
  'park-duchacki': require('../../assets/parks/park-duchacki.webp'),
  'park-decjusza': require('../../assets/parks/park-decjusza.webp'),
  'blonia-krakowskie': require('../../assets/parks/blonia-krakowskie.webp'),
  'park-fort-bronowice': require('../../assets/parks/park-fort-bronowice.webp'),
  'park-krakowski-im-marka-grechuty': require('../../assets/parks/park-krakowski-im-marka-grechuty.webp'),
  'park-ogrod-lobzow': require('../../assets/parks/park-ogrod-lobzow.webp'),
  'park-kleparski': require('../../assets/parks/park-kleparski.webp'),
  'park-im-henryka-jordana': require('../../assets/parks/park-im-henryka-jordana.webp'),
  'park-solvay': require('../../assets/parks/park-solvay.webp'),
  'park-im-tadeusza-kosciuszki': require('../../assets/parks/park-im-tadeusza-kosciuszki.webp'),
  'park-im-stanislawa-wyspianskiego': require('../../assets/parks/park-im-stanislawa-wyspianskiego.webp'),
  'park-zaczarowanej-dorozki': require('../../assets/parks/park-zaczarowanej-dorozki.webp'),
  'park-reduta': require('../../assets/parks/park-reduta.webp'),
  'park-kolejowy': require('../../assets/parks/park-kolejowy.webp'),
  'park-strzelecki': require('../../assets/parks/park-strzelecki.webp'),
  'park-jalu-kurka': require('../../assets/parks/park-jalu-kurka.webp'),
  'planty-krakowskie': require('../../assets/parks/planty-krakowskie.webp'),
  'park-im-wislawy-szymborskiej': require('../../assets/parks/park-im-wislawy-szymborskiej.webp'),
  'park-kurczaba': require('../../assets/parks/park-kurczaba.webp'),
  'park-wisniowy-sad': require('../../assets/parks/park-wisniowy-sad.webp'),
  'park-zielony-jar': require('../../assets/parks/park-zielony-jar.webp'),
  'park-luczanowice': require('../../assets/parks/park-luczanowice.webp'),
  'planty-bienczyckie': require('../../assets/parks/planty-bienczyckie.webp'),
  'planty-mistrzejowickie': require('../../assets/parks/planty-mistrzejowickie.webp'),
  'park-skalskiego': require('../../assets/parks/park-skalskiego.webp'),
  'park-czyzyny': require('../../assets/parks/park-czyzyny.webp'),
  'park-ogrod-plaszow': require('../../assets/parks/park-ogrod-plaszow.webp'),
  'park-aleksandry-polnoc': require('../../assets/parks/park-aleksandry-polnoc.webp'),
  'park-lilli-wenedy': require('../../assets/parks/park-lilli-wenedy.webp'),
  'park-aleksandry': require('../../assets/parks/park-aleksandry.webp'),
  'park-rzaka': require('../../assets/parks/park-rzaka.webp'),
  'park-kurdwanow': require('../../assets/parks/park-kurdwanow.webp'),
  'las-borkowski': require('../../assets/parks/las-borkowski.webp'),
  'park-macka-i-doroty': require('../../assets/parks/park-macka-i-doroty.webp'),
  'park-pychowicki': require('../../assets/parks/park-pychowicki.webp'),
  'park-krowoderski': require('../../assets/parks/park-krowoderski.webp'),
  'przylasek-rusiecki': require('../../assets/parks/przylasek-rusiecki.webp'),
  'zalew-nowohucki': require('../../assets/parks/zalew-nowohucki.webp'),
  'park-bagry-wielkie': require('../../assets/parks/park-bagry-wielkie.webp'),
  'staw-plaszowski': require('../../assets/parks/staw-plaszowski.webp'),
  'park-rzeczny-drwinka': require('../../assets/parks/park-rzeczny-drwinka.webp'),
  'park-zakrzowek': require('../../assets/parks/park-zakrzowek.webp'),
  'park-debnicki': require('../../assets/parks/park-debnicki.webp'),
  'park-nad-rudawa': require('../../assets/parks/park-nad-rudawa.webp'),
  'park-mlynowka-krolewska': require('../../assets/parks/park-mlynowka-krolewska.webp'),
  'park-rzeczny-tetmajera': require('../../assets/parks/park-rzeczny-tetmajera.webp'),
  'park-rzeczny-wilga': require('../../assets/parks/park-rzeczny-wilga.webp'),
  'park-nad-bialucha': require('../../assets/parks/park-nad-bialucha.webp'),
  'park-nad-sudolem': require('../../assets/parks/park-nad-sudolem.webp'),
  'park-dabie': require('../../assets/parks/park-dabie.webp'),
  'bulwary-wisly': require('../../assets/parks/bulwary-wisly.webp'),
};

export interface PhotoCredit {
  file: string;
  author: string;
  license: string;
  source: string;
}

// eslint-disable-next-line @typescript-eslint/no-require-imports
export const photoCredits: Record<string, PhotoCredit> = require('../../assets/parks/attribution.json');
