import { ImageSourcePropType } from 'react-native';

/**
 * AUTO-GENERATED by scripts/fetch-park-photos.mjs — do not edit by hand.
 * WebP heroes (max 960×640, q72) from Wikimedia Commons.
 * Attribution lives in assets/parks/attribution.json and MUST stay shipped
 * with the app (Commons licenses require author + license credit).
 */
export const parkPhotos: Record<string, ImageSourcePropType> = {
  'planty-krakowskie': require('../../assets/parks/planty-krakowskie.webp'),
  'park-im-henryka-jordana': require('../../assets/parks/park-im-henryka-jordana.webp'),
  'park-krakowski-im-marka-grechuty': require('../../assets/parks/park-krakowski-im-marka-grechuty.webp'),
  'park-im-wojciecha-bednarskiego': require('../../assets/parks/park-im-wojciecha-bednarskiego.webp'),
  'park-decjusza': require('../../assets/parks/park-decjusza.webp'),
  'park-jerzmanowskich': require('../../assets/parks/park-jerzmanowskich.webp'),
  'park-bialopradnicki': require('../../assets/parks/park-bialopradnicki.webp'),
  'park-ratuszowy': require('../../assets/parks/park-ratuszowy.webp'),
  'park-szwedzki': require('../../assets/parks/park-szwedzki.webp'),
  'park-jalu-kurka': require('../../assets/parks/park-jalu-kurka.webp'),
  'park-im-stefana-zeromskiego': require('../../assets/parks/park-im-stefana-zeromskiego.webp'),
  'park-wandy': require('../../assets/parks/park-wandy.webp'),
  'park-solvay': require('../../assets/parks/park-solvay.webp'),
  'park-im-tadeusza-kosciuszki': require('../../assets/parks/park-im-tadeusza-kosciuszki.webp'),
  'park-reduta': require('../../assets/parks/park-reduta.webp'),
  'park-zaczarowanej-dorozki': require('../../assets/parks/park-zaczarowanej-dorozki.webp'),
  'park-tysiaclecia': require('../../assets/parks/park-tysiaclecia.webp'),
  'park-im-stanislawa-wyspianskiego': require('../../assets/parks/park-im-stanislawa-wyspianskiego.webp'),
  'park-lotnikow-polskich': require('../../assets/parks/park-lotnikow-polskich.webp'),
  'park-im-wislawy-szymborskiej': require('../../assets/parks/park-im-wislawy-szymborskiej.webp'),
  'park-kleparski': require('../../assets/parks/park-kleparski.webp'),
  'park-duchacki': require('../../assets/parks/park-duchacki.webp'),
  'park-wadow': require('../../assets/parks/park-wadow.webp'),
  'park-stacja-wisla': require('../../assets/parks/park-stacja-wisla.webp'),
  'park-strzelecki': require('../../assets/parks/park-strzelecki.webp'),
  'las-wolski': require('../../assets/parks/las-wolski.webp'),
  'lasek-mogilski': require('../../assets/parks/lasek-mogilski.webp'),
  'lasek-legowski': require('../../assets/parks/lasek-legowski.webp'),
  'las-borkowski': require('../../assets/parks/las-borkowski.webp'),
  'park-lesny-witkowice': require('../../assets/parks/park-lesny-witkowice.webp'),
  'park-skalki-twardowskiego': require('../../assets/parks/park-skalki-twardowskiego.webp'),
  'panienskie-skaly': require('../../assets/parks/panienskie-skaly.webp'),
  'park-aleksandry': require('../../assets/parks/park-aleksandry.webp'),
  'park-kurdwanow': require('../../assets/parks/park-kurdwanow.webp'),
  'park-rzaka': require('../../assets/parks/park-rzaka.webp'),
  'planty-mistrzejowickie': require('../../assets/parks/planty-mistrzejowickie.webp'),
  'park-czyzyny': require('../../assets/parks/park-czyzyny.webp'),
  'park-wisniowy-sad': require('../../assets/parks/park-wisniowy-sad.webp'),
  'park-lilli-wenedy': require('../../assets/parks/park-lilli-wenedy.webp'),
  'park-zielony-jar': require('../../assets/parks/park-zielony-jar.webp'),
  'park-krowoderski': require('../../assets/parks/park-krowoderski.webp'),
  'park-bonarka': require('../../assets/parks/park-bonarka.webp'),
  'park-macka-i-doroty': require('../../assets/parks/park-macka-i-doroty.webp'),
  'park-gorka-narodowa': require('../../assets/parks/park-gorka-narodowa.webp'),
  'park-mydlniki': require('../../assets/parks/park-mydlniki.webp'),
  'park-luczanowice': require('../../assets/parks/park-luczanowice.webp'),
  'park-piaski-wielkie': require('../../assets/parks/park-piaski-wielkie.webp'),
  'park-wzgorza-krzeslawickie': require('../../assets/parks/park-wzgorza-krzeslawickie.webp'),
  'zalew-nowohucki': require('../../assets/parks/zalew-nowohucki.webp'),
  'park-zakrzowek': require('../../assets/parks/park-zakrzowek.webp'),
  'park-dabie': require('../../assets/parks/park-dabie.webp'),
  'staw-plaszowski': require('../../assets/parks/staw-plaszowski.webp'),
  'park-rzeczny-wilga': require('../../assets/parks/park-rzeczny-wilga.webp'),
  'park-mlynowka-krolewska': require('../../assets/parks/park-mlynowka-krolewska.webp'),
  'park-nad-sudolem': require('../../assets/parks/park-nad-sudolem.webp'),
  'przylasek-rusiecki': require('../../assets/parks/przylasek-rusiecki.webp'),
  'staw-dabski': require('../../assets/parks/staw-dabski.webp'),
  'staw-przy-kaczencowej': require('../../assets/parks/staw-przy-kaczencowej.webp'),
  'park-debnicki': require('../../assets/parks/park-debnicki.webp'),
};

export interface PhotoCredit {
  file: string;
  author: string;
  license: string;
  source: string;
}

// eslint-disable-next-line @typescript-eslint/no-require-imports
export const photoCredits: Record<string, PhotoCredit> = require('../../assets/parks/attribution.json');
